Exercise 2
arun-gopal/DevOps-Course-Starter pull request #2
Opened 2021-05-09 01:27 UTC by arun-gopal

Integration with Trello API

![Screenshot from 2021-05-09 16-10-54](https://user-images.githubusercontent.com/81308568/117577313-321fb100-b0e1-11eb-83cb-6d0014e7d1a2.png)

2021-05-11 08:52 UTC, JackMead requested changes
This looks good, I was able to easily follow your instructions and view/create/move todos on the site backed by Trello. I've left a few thoughts below, but importantly you've not done Part 5 here - creating a class for to-do items - so we should do that before this can be approved. Feel free to get in touch if you have any questions regarding that

2021-05-11 08:52 UTC, JackMeadDev commented on README.md
> +TRELLO_API_KEY=<YOUR_API_KEY>
Nice docs, but it would be good to also add these to your .env.template file so that a user has a natural prompt there as well

2021-05-11 08:52 UTC, JackMeadDev commented on todo_app/trello_client.py
> +def get_cards_from_board_items():
I can't see any evidence that you use this function (or the one it calls) - let's clear it out in that case, we can always recover it from git if we want it later

2021-05-11 08:52 UTC, JackMeadDev commented on todo_app/app.py
> -from todo_app.data.session_items import get_items, add_item
It looks like you no longer user `session_items` at all - we should get rid of that now in that case (and if that's correct, we could also get rid of the config/secret key as we no longer need those)

2021-05-11 08:52 UTC, JackMeadDev commented on todo_app/app.py
> +    return render_template('index.html', todo_items=get_cards_from_todo_list(), done_items=get_cards_from_done_list())
Here you're still directly passing through the responses json to the template - this doesn't give us much control over the items we're passing to the frontend, and means they are closely tied to Trello. Instead, we should move to converting Trello's responses into a class under our control, and using that elsewhere in our code.

2021-05-16 20:21 UTC, arun-gopal commented on README.md
> +TRELLO_API_KEY=<YOUR_API_KEY>
Done, thanks.

2021-05-16 20:21 UTC, arun-gopal commented on todo_app/app.py
> -from todo_app.data.session_items import get_items, add_item
Done, thanks.

2021-05-16 20:22 UTC, arun-gopal commented on todo_app/trello_client.py
> +def get_cards_from_board_items():
Removed it, thanks.

2021-05-16 21:43 UTC, arun-gopal commented
> This looks good, I was able to easily follow your instructions and view/create/move todos on the site backed by Trello. I've left a few thoughts below, but importantly you've not done Part 5 here - creating a class for to-do items - so we should do that before this can be approved. Feel free to get in touch if you have any questions regarding that

This has been completed now, thanks.

2021-05-16 21:43 UTC, arun-gopal commented on todo_app/app.py
> +    return render_template('index.html', todo_items=get_cards_from_todo_list(), done_items=get_cards_from_done_list())
This has been completed as suggested. Thanks.

2021-05-24 12:54 UTC, Jonesey13 approved these changes
Looks good to me! Free free to merge this PR in when you are ready 👍

2021-05-26 12:53 UTC, merged